---
name: ((deployment_name))

instance_groups:
- name: redis
  azs: [((default_az))]
  instances: ((node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk_type: ((default_persistent_disk_type))
  networks:
  - name: ((default_network))
  jobs:
  - name: redis
    release: redis-service
    consumes:
      slave_conn: nil
    properties:
      bind: ((redis_bind))
      port: '0'
      password: ((redis_password))
      admin_password: ((redis_admin_password))
      exporter_password: ((redis_exporter_password))
      maxmemory: ((redis_maxmemory))
      maxmemory_policy: ((redis_maxmemory_policy))
      cluster_enabled: ((redis_cluster_enabled))
      replica_password: ((redis_replica_password))
      cluster_replicas_per_node: ((replicas_per_node_count))
      tls: true
      tls_keys: ((redis_keys))
      tls_dh_length: ((redis_dh_length))
      tls_cluster: true
  - name: redis_check
    release: redis-service
    consumes:
      slave_conn: nil
    properties:
      tls_keys: ((redis_check_keys))
  - name: redis_exporter
    release: redis-service
    properties:
      skip_tls_verification: true
      tls_keys: ((redis_exporter_keys))
- name: broker
  azs: [((default_az))]
  instances: 1
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk_type: ((default_persistent_disk_type))
  networks:
  - name: ((default_network))
  jobs:
  - name: redis_broker
    release: redis-service
    consumes:
      slave_conn: nil
    properties:
      bind: ((redis_bind))
      password: ((redis_broker_password))
      tls_keys: ((redis_broker_keys))
  - name: redis_broker_check
    release: redis-service

variables:
- name: redis_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_admin_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_exporter_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_replica_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_broker_password
  type: password
  parameters:
    length: ((password_length))
- name: ((redis_ca))
  type: certificate
  options:
    common_name: ((deployment_name))
    organization: 'orange.com'
    key_length: ((ca_key_length))
    duration: ((certificate_duration))
    is_ca: true
    self_sign: true
- name: redis_keys
  type: certificate
  options:
    ca: ((redis_ca))
    common_name: 'Server'
    organization: 'orange.com'
    organization_unit: ((deployment_name))
    key_length: ((private_key_length))
    duration: ((certificate_duration))
- name: redis_check_keys
  type: certificate
  options:
    ca: ((redis_ca))
    common_name: 'Client'
    organization: 'orange.com'
    organization_unit: ((deployment_name))
    key_length: ((private_key_length))
    duration: ((certificate_duration))
- name: redis_broker_keys
  type: certificate
  options:
    ca: ((redis_ca))
    common_name: 'Broker'
    organization: 'orange.com'
    organization_unit: ((deployment_name))
    key_length: ((private_key_length))
    duration: ((certificate_duration))
- name: redis_exporter_keys
  type: certificate
  options:
    ca: ((redis_ca))
    common_name: 'Exporter'
    organization_unit: ((deployment_name))
    organization: 'orange.com'
    key_length: ((private_key_length))
    duration: ((certificate_duration))

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

releases:
- name: redis-service
  version: latest

update:
  canaries: 2
  canary_watch_time: 60000-120000
  max_in_flight: 2
  update_watch_time: 60000-120000
  serial: false
