common/proxy-env.sh:
  size: 591
  object_id: 8066d01e-802d-43ef-7928-98f14636e715
  sha: sha256:d28278ab95b80b62cc3ebbfefdc64eeb16085d67baae8612ae30a76fb9997c95
common/utils.sh:
  size: 2821
  object_id: a28b3d0c-6cba-4359-4780-c7aa369720fe
  sha: sha256:2b63351260cb05c7ca4d7d849c3f55e3a636a816d3244bd0698dc37e2485bce2
openjdk/openjdk-13.0.2_linux-x64_bin.tar.gz:
  size: 195812001
  object_id: 1de2f0d7-be13-450f-560b-4fa85138c76a
  sha: sha256:acc7a6aabced44e62ec3b83e3b5959df2b1aa6b3d610d58ee45f0c21a7821a71
redis/redis-5.0.10.tar.gz:
  size: 1990507
  object_id: 8372ac5c-7622-4e02-7132-2326c24b9331
  sha: sha256:e30a5e7d1593a715cdda2a82deb90190816d06c9d1dc1ef5b36874878c683382
redis_broker-1.5/broker-1.5-0.0.1-SNAPSHOT.jar:
  size: 21609535
  object_id: 99651425-e068-47db-50c6-c51608d956dd
  sha: sha256:e5f86e0f113df5094c8c3ee96a4d1156abf730a3fd8035a386996d76e7f2e373
redis_broker/broker-0.0.1-SNAPSHOT.jar:
  size: 27296565
  object_id: 8cd1a16b-92be-4197-4f94-08693d8ae2a6
  sha: sha256:811004a864a991c8ab2af3c987141cf5c0ca54e02aca6ee90f325e964d82d97c
redis_exporter/redis_exporter-v1.3.5.linux-amd64.tar.gz:
  size: 3376514
  object_id: c6f9f3b1-a863-4793-52f5-55d133c721c9
  sha: sha256:bb408128cb4c3024c8532dae3539080349687cc96cbab51a1e06e9a15519b874
redis_exporter/redis_exporter-v1.16.0.linux-amd64.tar.gz:
  size: 3264022
  object_id: ff27ef12-1b6b-455e-615a-515b95d3ab3f
  sha: sha256:de350fe8638cd29eca2fde11d26bf59d429504c6a8f1752bf9c1697c5689f425
redis_sentinel_exporter/redis_sentinel_exporter-1.3.0.linux-amd64.tar.gz:
  size: 3217655
  object_id: ab97ab32-3dc3-4de5-7a31-2b23aa5f23f1
  sha: sha256:d74039cc92c914dccfb907ea6fb140377d13843193b772946ca7ec814a507b2e
redis_sentinel_exporter/redis_sentinel_exporter-1.7.1.linux-amd64.tar.gz:
  size: 3810651
  object_id: 0b7e807d-77b5-4580-76d7-dc7e2b86cde1
  sha: sha256:e0475ce53945afb4d3a87b6a786a4ed0a5458f2a09800ef0aa62c8d89ef54d8d
